### PR TITLE
Update App.config

### LINKED ISSUE #2: missing GUID for Balanced
the balanced powermode overlay plan has a guid of `00000000-0000-0000-0000-000000000000`

### PR DESCRIPTION
**Pull request by bcutter**
Fixes #2, tested with Win 11 where winver=22H2 and 23H2

### CODE REVIEW

**Comment by jredfox** [comment]
No the pull request is wrong all you did was simply replace a valid value with balanced. There are now 4 values not 3. You can take a look at my re-write of his program to fit my needs to fix it
https://pastebin.com/LZR5zenn

**Comment by bcutter** [comment]
TBO: I don't care. I adjusted what did not work for me, now it works. Thought it would help others too, created the PR. Story end.

**Comment by jredfox** [comment]
> TBO: I don't care. I adjusted what did not work for me, now it works. Thought it would help others too, created the PR. Story end.

Editing the config will just change performance aka "better performance" to "balanced"

**Comment by bcutter** [comment]
Closed because complaining other users indicate this PR does not add any benefit (which it did and does for me, anyway).

**Pull request closed without merging**
